name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - ""  

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: Username
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Write here the bug you encountered!
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Attach your screenshots
      placeholder: Click in this area then drag & drop your file(s)
    validations:
      required: false

  - type: textarea
    id: repro
    attributes:
      label: How it happened?
      placeholder: Give us the most detailed sequence of actions you did to get your bug
    validations:
      required: true

  - type: textarea
    id: statistics
    attributes:
      label: What are your performances on Menyr?
      placeholder: Screen what you have in the statistics menu on Menyr and paste the screenshot here
    validations:
      required: false

  - type: textarea
    id: version
    attributes:
      label: Which version of Menyr are you using ?
      placeholder: Write down the version you're currently playing on
    validations:
      required: true