blank_issues_enabled: false
contact_links:
  - name: Community Feature Request
    url: https://portal.productboard.com/ycntuexygoaukq1vqftharus/tabs/4-roadmap
    about: Please propose and follow new features here.
