blank_issues_enabled: false
contact_links:
  - name: Community Feature Request
    url: https://portal.productboard.com/ycntuexygoaukq1vqftharus/tabs/4-roadmap
    about: If there is a feature you would like to see in Menyr, please follow this link.
